### ISSUE TITLE
denote-fz-dired-sorted: Numbers with two or more digits in the third or higher field incorrectly sorted

### ISSUE THREAD

**Issue by phmcc** [MirkoHernandez/denote-folgezettel#3]
Again, excellent package.  In doing a little bit of stress testing, I've noticed that—with the exception of the first numeric field—`denote-fz-dired-sorted` sorts numbers by whole number at the end of the previous letter field; i.e.,

```
2b8
2b9
2c1
2c2
[...]
2z1
2b10
2b11
```

By contrast, when the number is in the first numeric field, `denote-fz-dired-sorted` sorts things correctly:

```
[...]
8a
8b
9a1
9a2
10a
10b
```

Is it possible to tweak the sorting algorithm to take these downstream numeric fields into account as well?  Thanks!

**Comment by MirkoHernandez** [comment]
Hello @matogoro, thanks for reporting this issue, the sorting algorithm is a bit janky right now, hopefully there are just a few unhandled cases left. I will see to it today and probably refactor the algorithm in the future.
